export type RootStackParamList = {
  Home: undefined;
  SetUserName: undefined;
  UpdateUserName: undefined;
  Quiz: undefined;
  Introduction: undefined;
  Instructions: undefined;
  LakeRiver: undefined;
  LakeRiverRepeat: undefined;
  LakeRiverResults: { points: number, data: any };
  LakeRiverResultsRepeat: { points: number, data: any };
  LakeRiverLoseScreen: undefined;
  LakeRiverLoseScreenR: undefined;
  Mountain: undefined;
  MountainRepeat: undefined;
  MountainResults: { points: number, data: any };
  MountainResultsRepeat: { points: number, data: any };
  MountainLoseScreen: undefined;
  MountainLoseScreenR: undefined;
  LoseScreen: undefined;
  Nomoi1: undefined;
  Nomoi1R: undefined;
  Nomoi2: undefined;
  Nomoi2R: undefined;
  Nomoi3: undefined;
  Nomoi3R: undefined;
  Nomoi4: undefined;
  Nomoi4R: undefined;
  Nomoi5: undefined;
  Nomoi5R: undefined;
  Nomoi6: undefined;
  Nomoi6Final: { points: number, data: any };
  Nomoi6R: undefined;
  NomoiResultTemplate: undefined;
  NomoiResult1: { points: number, data: any };
  NomoiResult2: { points: number, data: any };
  NomoiResult3: { points: number, data: any };
  NomoiResult4: { points: number, data: any };
  NomoiResult5: { points: number, data: any };
  NomoiResult6: { points: number, data: any };
  NomoiLoseScreen1: undefined;
  NomoiLoseScreen1R: undefined;
  NomoiLoseScreen2: undefined;
  NomoiLoseScreen2R: undefined;
  NomoiLoseScreen3: undefined;
  NomoiLoseScreen3R: undefined;
  NomoiLoseScreen4: undefined;
  NomoiLoseScreen4R: undefined;
  NomoiLoseScreen5: undefined;
  NomoiLoseScreen5R: undefined;
  NomoiLoseScreen6: undefined;
  NomoiLoseScreen6R: undefined;
  GeneralQuestions1: undefined;
  GeneralQuestions1R: undefined;
  // GeneralQuestionsResult1: undefined;
  GeneralQuestionsResult1: { points: number, data: any };
  GeneralQuestionsResult1R: { points: number, data: any };
  GenQResLoseScreen: undefined;
  GenQResLoseScreenR: undefined;
  GenerQuestTemplate: { points: number, data: any }
};
