import { StyleSheet, Dimensions, Platform } from "react-native";
const { height } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerImg: {
    flexDirection: "row",
    gap: 10,
    marginLeft: 0,
    alignItems: "center",
  },
  gradient: {
    flex: 1,
    flexDirection: "row",
    padding: 0,
  },
  characterContainer: {
    width: 100,
    alignItems: "center",
    marginTop: Platform.OS === "ios" ? 70 : height > 900 ? 100 : 55,
  },
  character: {
    width: 80,
    height: 80,
    borderRadius: 40,
    // marginBottom: 20,
    borderWidth: 3,
    borderColor: "#FFD700",
  },
  userName: {
    position: "absolute",
    top: 90,
    left: 0,
    width: 150,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  gameOverUserWin: {
    width: height > 900 ? 120 : 90,
    height: height > 900 ? 120 : 90,
    alignSelf: "center",
    borderRadius: 20,
    borderColor: "green",
    borderWidth: 5,
  },
  mockName: {
    position: "absolute",
    top: 90,
    right: -25,
    width: 150,
    justifyContent: "center",
    alignItems: "center",
  },
  gameOverMockWin: {
    width: height > 900 ? 120 : 90,
    height: height > 900 ? 120 : 90,
    alignSelf: "center",
    borderRadius: 20,
    borderColor: "red",
    borderWidth: 5,
  },
  score: {
    color: "#FFD700",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 4,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  thinkingIndicator: {
    // width: 120,
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginTop: 8,
  },
  thinkingText: {
    color: "#FFD700",
    fontSize: 14,
    paddingHorizontal: 20,
    fontWeight: "600",
  },
  sideContainer: {
    alignItems: "center",
    justifyContent: "center",
  },
  boxesContainer: {
    height: "60%",
    justifyContent: "space-around",
  },
  answerBox: {
    width: 40,
    height: 40,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 8,
    marginVertical: 5,
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.3)",
  },
  centerContainer: {
    flex: 1,
    // marginTop: '55%',
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "20%",
    padding: 10,
  },
  questionContainer: {
    position: "absolute",
    bottom: height > 900 ? "15%" : "8%",
    width: "90%",
    backgroundColor: "rgba(255,255,255,0.1)",
    padding: 20,
    borderRadius: 15,
    paddingVertical: 20,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  questionNumber1: {
    position: "absolute",
    top: -30,
    left: 20,
    // transform: [{ rotate: "-10deg" }],
    fontSize: 14,
    color: "#FFD700",
    opacity: 0.8,
    marginBottom: 10,
    textAlign: "center",
    fontWeight: "600",
  },
  questionNumber2: {
    position: "absolute",
    top: -30,
    right: 20,
    // transform: [{ rotate: "-10deg" }],
    fontSize: 14,
    color: "#FFD700",
    opacity: 0.8,
    marginBottom: 10,
    textAlign: "center",
    fontWeight: "600",
  },
  battleCoins:{
    padding: 5,
    borderRadius: 10,
    position: "absolute",
    right: 20,
    top: -30,
    zIndex: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    opacity: 0.8
  },
  questionText: {
    fontSize: 24,
    fontWeight: "600",
    textAlign: "center",
    color: "#FFFFFF",
    paddingVertical: 20,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 5,
  },
  optionsContainer: {
    width: "100%",
    maxWidth: 400,
    gap: 12,
  },
  optionButton: {
    borderRadius: 12,
    overflow: "hidden",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  optionButtonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
  optionGradient: {
    padding: 16,
    alignItems: "center",
  },
  optionText: {
    fontSize: 18,
    color: "#FFFFFF",
    fontWeight: "500",
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 3,
  },
  text1: {
    fontSize: 12,
    fontFamily: "Poppins-Bold",
    color: "#d6d6d6",
    textAlign: "right",
  },
  text2: {
    fontSize: height > 900 ? 22 : 18,
    fontFamily: "Poppins-Bold",
    color: "#d6d6d6",
    textAlign: "center",
    paddingBottom: 20,
  },
  text3Container: {
    width: "90%",
    backgroundColor: "rgba(255,255,255,0.1)",
    padding: 20,
    borderRadius: 15,
    paddingVertical: 20,
    marginLeft: 10,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  text3: {
    fontSize: height > 900 ? 24 : 20,
    fontFamily: "Poppins-Bold",
    color: "#d6d6d6",
    textAlign: "center",
  },
  returnQuizBtn: {
    position: "absolute",
    top: Platform.OS === "ios" ? 20 : height > 900 ? 20 : 10,
    left: 0,
    paddingVertical: 30,
    paddingHorizontal: 10,
    flexDirection: "row",
  },
});

export default styles;
