import { StyleSheet, Dimensions } from "react-native";
const { height } = Dimensions.get('window');

const styles = StyleSheet.create({
  containerInfo: {
    textAlign: "center",
    marginTop: "8%",
    marginBottom: "2%",
  },
  levelBox: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 30,
    marginBottom: 5,
  },
  levelBox1: {
    // backgroundColor: 'darkblue',
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 30,
    paddingTop: 30,
  },
  counterBox: {
    padding: 10,
    backgroundColor: "green",
    borderRadius: 20,
    // width: 35,
    // height: 30,
  },
  counterNumber: {
    color: "white",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 14,
  },
  progressContainerInfo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: "10%",
  },
  progressBarBack: {
    backgroundColor: "white",
    // backgroundColor: "green",
    width: height>900? "60%":"80%",
    flexDirection: "row",
    alignItems: "center",
    height: 7,
    borderRadius: 20,
    justifyContent: "center",
    marginTop: "3%",
    marginLeft: "auto",
    marginRight: "auto",
  },
  quizContainer: {
    flex: 1,
    // flexDirection: 'row',
    justifyContent: "space-between",
    marginTop: 10,
    backgroundColor: "lightgray",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
    shadowColor: "lightblue",
    shadowOffset: { width: 5, height: 8 },
    shadowRadius: 20,
    elevation: 10,
  },
  quizContainer1: {
    flex: 1,
    justifyContent: "space-between",
    marginTop: 10,
    backgroundColor: "lightgray",
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
  },
  androidProp: {
    shadowColor: "green",
    elevation: 20,
  },
  quizContainer2: {
    flex: 1,
    justifyContent: "space-between",
    marginTop: 10,
    backgroundColor: "lightgray",
    // paddingVertical: 20,
    // paddingHorizontal: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
    shadowColor: "#dd0530",
    shadowOffset: { width: 5, height: 8 },
    // shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  image: {
    borderRadius: 10,
    marginVertical: 10,
    width: "100%",
    height: 150,
  },
  question: {
    // marginLeft: 20,
    textAlign: "center",
    marginTop: 10,
    paddingHorizontal: 10,
    fontSize: height>900? 20: 16,
    fontWeight: "bold",
    height: 70
  },
  answersContainer: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 10,
    paddingTop: 5,
  },
  correctAnswer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "green",
    width: "47%",
    height: height>900 ? 120:90,
    borderRadius: 6,
    margin: "1.5%",
  },
  wrongAnswer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#dd0530",
    width: "47%",
    height: height>900 ? 120:90,
    borderRadius: 6,
    margin: "1.5%",
  },
  borderAnswer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#006cfa",
    width: "47%",
    height: height>900 ? 120:90,
    borderRadius: 6,
    margin: "1.5%",
  },
  feedBackArea: {
    // backgroundColor: "darkblue",
    paddingTop: 20,
    marginHorizontal: 20,
  },
  nextQueButton: {
    backgroundColor: "magenta",
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    width: 140,
    borderRadius: 6,
    // marginHorizontal: "auto",
  },
  nextQueButton1: {
    marginLeft: "auto",
    marginRight: "auto",
    backgroundColor: "green",
    padding: 14,
    alignItems: "center",
    // justifyContent: 'center',
    width: 160,
    borderRadius: 6,
    // marginHorizontal: "auto",
  },
  nextQueButton2: {
    backgroundColor: "#dd0530",
    padding: 14,
    alignItems: "center",
    width: 160,
    borderRadius: 6,
    marginLeft: "auto",
    marginRight: "auto",
    // marginHorizontal: "auto",
  },
  btnInfoHeart: {
    position: "absolute",
    left: -50,
    width: 50,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    // backgroundColor: 'yellow'
  },
});

export default styles;
