import GeneralQuestions1 from './Quizzes/GeneralQuestions1'
import GeneralQuestions1R from './Quizzes/GeneralQuestions1R'
import GeneralQuestions2 from './Quizzes/GeneralQuestions2'
import GeneralQuestions2R from './Quizzes/GeneralQuestions2R'
import GeneralQuestions3 from './Quizzes/GeneralQuestions3'
import GeneralQuestions3R from './Quizzes/GeneralQuestions3R'
import GeneralQuestions4 from './Quizzes/GeneralQuestions4'
import GeneralQuestions4R from './Quizzes/GeneralQuestions4R'
import GeneralQuestions5 from './Quizzes/GeneralQuestions5'
import GeneralQuestions5R from './Quizzes/GeneralQuestions5R'
import GQLoseScreen1 from './Quizzes/GQLoseScreen1'
import GQLoseScreen2 from './Quizzes/GQLoseScreen2'
import GQLoseScreen3 from './Quizzes/GQLoseScreen3'
import GQLoseScreen4 from './Quizzes/GQLoseScreen4'
import GQLoseScreen5 from './Quizzes/GQLoseScreen5'
import GQLoseScreenR1 from './Quizzes/GQLoseScreenR1'
import GQLoseScreenR2 from './Quizzes/GQLoseScreenR2'
import GQLoseScreenR3 from './Quizzes/GQLoseScreenR3'
import GQLoseScreenR4 from './Quizzes/GQLoseScreenR4'
import GQLoseScreenR5 from './Quizzes/GQLoseScreenR5'

export {GeneralQuestions1, GeneralQuestions1R, GeneralQuestions2, GeneralQuestions2R,  GeneralQuestions3, GeneralQuestions3R,GeneralQuestions4, GeneralQuestions4R, GeneralQuestions5, GeneralQuestions5R, GQLoseScreen1, GQLoseScreen2,GQLoseScreen3,GQLoseScreen4,GQLoseScreen5,GQLoseScreenR1,GQLoseScreenR2,GQLoseScreenR3,GQLoseScreenR4,GQLoseScreenR5}
